name: Lint and Test Charts

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          submodules: recursive
          fetch-depth: 0
